# Generated by Django 4.2.3 on 2023-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRIImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='mri_scans/')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
